services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mumulbo/mmb-notification-service
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: ./gradlew bootRun
    networks:
      - external-net