server:
  port: ${SERVICE_PORT:8080}

spring:
  web:
    resources:
      static-locations: classpath:/static/

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27018}/notification?socketTimeoutMS=10000&connectTimeoutMS=10000
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:mmb-kafka}:${KAFKA_PORT:9092}


logging:
  level:
    root: ${LOG_ROOT_LEVEL:info}
    org.springframework.web: ${LOG_WEB_LEVEL:debug}     # Spring 내부 로그 줄이기
    com.mumulbo: ${LOG_APP_LEVEL:debug}                # 내 애플리케이션 패키지만 DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name:   # 파일 로그 비활성화 (없애도 무방)
